spring:
  profiles: dev
  http:
    multipart:
      max-file-size: 130720MB
      max-request-size: 130720MB
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://localhost:3306/formulario
    username: root
    password: ''
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      minimum-idle: 1
      maximum-pool-size: 2
  jackson:
    mapper:
      default_view_inclusion: true
eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
mybatis:
  config-location: mybatis-config.xml  
